name: hips

channels:
    - conda-forge
    - astropy

dependencies:
    - python=3.6
    - numpy
    - astropy
    - healpy
    - reproject
    - matplotlib
    - tqdm
    # There's a problem with Sphinx 1.6 with astropy-helpers
    # For now, we pin the Sphinx version to something that works
    - sphinx==1.5.6
    - pip:
        - sphinx_rtd_theme
