# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - EVENT_TYPE='pull_request push'
        - CONDA_DEPENDENCIES='astropy-healpix scikit-image Pillow reproject matplotlib tqdm aiohttp'
#        - PIP_DEPENDENCIES='git+https://github.com/astropy/astropy-healpix.git#egg=astropy_healpix'
        - CONDA_CHANNELS='conda-forge astropy-ci-extras astropy'
        - SETUP_XVFB=True
        - DEBUG=True
        - ASTROPY_USE_SYSTEM_PYTEST=1
        - FETCH_HIPS_EXTRA=true

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'

matrix:
    # Don't wait for allowed failures
    fast_finish: true

    include:
        # Main build -- used for coverage
        - os: linux
          env: SETUP_CMD='test --coverage --remote-data -V'

        # Docs build
        - os: linux
          env: SETUP_CMD='build_docs -w'
               PIP_DEPENDENCIES='sphinx_rtd_theme'

        # Check that install / tests work with minimal required dependencies
        - os: linux
          env: SETUP_CMD='test -V'
               CONDA_DEPENDENCIES='astropy-healpix scikit-image Pillow'

        # Try MacOS X
        - os: osx
          env: SETUP_CMD='test'

        # Try older Numpy versions
        - os: linux
          env: NUMPY_VERSION=1.11

        # Try numpy pre-release
        - os: linux
          env: NUMPY_VERSION=prerelease
               EVENT_TYPE='pull_request push cron'

        # Run static code analysis
        - os: linux
          env: MAIN_CMD='make code-analysis' SETUP_CMD=''
               PIP_DEPENDENCIES='mypy pycodestyle'


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

    - if $FETCH_HIPS_EXTRA; then
          git clone https://github.com/hipspy/hips-extra.git $HOME/hips-extra;
          export HIPS_EXTRA=${HOME}/hips-extra;
      fi


script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line below.
    # The coveragerc file may be customized as needed for your package.
     - if [[ $SETUP_CMD == *coverage* ]]; then coveralls --rcfile='hips/tests/coveragerc'; fi
